#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Sep 19 18:52:31 AEST 2023
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
